/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AppAchievementsRouteImport } from './routes/_app.achievements'
import { Route as AppAiRouteImport } from './routes/_app.ai'
import { Route as AppAssessmentsRouteImport } from './routes/_app.assessments'
import { Route as AppCertificatesRouteImport } from './routes/_app.certificates'
import { Route as AppContinueRouteImport } from './routes/_app.continue'
import { Route as AppCoursesRouteImport } from './routes/_app.courses'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppFinanceRouteImport } from './routes/_app.finance'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppRankingRouteImport } from './routes/_app.ranking'
import { Route as AppRoleplayRouteImport } from './routes/_app.roleplay'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppCoursesIndexRouteImport } from './routes/_app.courses.index'
import { Route as AppCoursesCourseIdRouteImport } from './routes/_app.courses.$courseId'
import { Route as AppRoleplaySimulationIdRouteImport } from './routes/_app.roleplay.$simulationId'
import { Route as AppCoursesCourseIdIndexRouteImport } from './routes/_app.courses.$courseId.index'
import { Route as AppCoursesCourseIdLessonsLessonIdRouteImport } from './routes/_app.courses.$courseId.lessons.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessmentsRoute = AppAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificatesRoute = AppCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AppRoute,
} as any)
const AppContinueRoute = AppContinueRouteImport.update({
  id: '/continue',
  path: '/continue',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesRoute = AppCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingRoute = AppRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AppRoute,
} as any)
const AppRoleplayRoute = AppRoleplayRouteImport.update({
  id: '/roleplay',
  path: '/roleplay',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesIndexRoute = AppCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCoursesRoute,
} as any)
const AppCoursesCourseIdRoute = AppCoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => AppCoursesRoute,
} as any)
const AppRoleplaySimulationIdRoute = AppRoleplaySimulationIdRouteImport.update({
  id: '/$simulationId',
  path: '/$simulationId',
  getParentRoute: () => AppRoleplayRoute,
} as any)
const AppCoursesCourseIdIndexRoute = AppCoursesCourseIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCoursesCourseIdRoute,
} as any)
const AppCoursesCourseIdLessonsLessonIdRoute =
  AppCoursesCourseIdLessonsLessonIdRouteImport.update({
    id: '/lessons/$lessonId',
    path: '/lessons/$lessonId',
    getParentRoute: () => AppCoursesCourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/achievements': typeof AppAchievementsRoute
  '/ai': typeof AppAiRoute
  '/assessments': typeof AppAssessmentsRoute
  '/certificates': typeof AppCertificatesRoute
  '/continue': typeof AppContinueRoute
  '/courses': typeof AppCoursesRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/finance': typeof AppFinanceRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/ranking': typeof AppRankingRoute
  '/roleplay': typeof AppRoleplayRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/courses/$courseId': typeof AppCoursesCourseIdRouteWithChildren
  '/roleplay/$simulationId': typeof AppRoleplaySimulationIdRoute
  '/courses/': typeof AppCoursesIndexRoute
  '/courses/$courseId/': typeof AppCoursesCourseIdIndexRoute
  '/courses/$courseId/lessons/$lessonId': typeof AppCoursesCourseIdLessonsLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/achievements': typeof AppAchievementsRoute
  '/ai': typeof AppAiRoute
  '/assessments': typeof AppAssessmentsRoute
  '/certificates': typeof AppCertificatesRoute
  '/continue': typeof AppContinueRoute
  '/dashboard': typeof AppDashboardRoute
  '/finance': typeof AppFinanceRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/ranking': typeof AppRankingRoute
  '/roleplay': typeof AppRoleplayRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/roleplay/$simulationId': typeof AppRoleplaySimulationIdRoute
  '/courses': typeof AppCoursesIndexRoute
  '/courses/$courseId': typeof AppCoursesCourseIdIndexRoute
  '/courses/$courseId/lessons/$lessonId': typeof AppCoursesCourseIdLessonsLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/achievements': typeof AppAchievementsRoute
  '/_app/ai': typeof AppAiRoute
  '/_app/assessments': typeof AppAssessmentsRoute
  '/_app/certificates': typeof AppCertificatesRoute
  '/_app/continue': typeof AppContinueRoute
  '/_app/courses': typeof AppCoursesRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/finance': typeof AppFinanceRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/ranking': typeof AppRankingRoute
  '/_app/roleplay': typeof AppRoleplayRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/courses/$courseId': typeof AppCoursesCourseIdRouteWithChildren
  '/_app/roleplay/$simulationId': typeof AppRoleplaySimulationIdRoute
  '/_app/courses/': typeof AppCoursesIndexRoute
  '/_app/courses/$courseId/': typeof AppCoursesCourseIdIndexRoute
  '/_app/courses/$courseId/lessons/$lessonId': typeof AppCoursesCourseIdLessonsLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/achievements'
    | '/ai'
    | '/assessments'
    | '/certificates'
    | '/continue'
    | '/courses'
    | '/dashboard'
    | '/finance'
    | '/notifications'
    | '/profile'
    | '/ranking'
    | '/roleplay'
    | '/settings'
    | '/courses/$courseId'
    | '/roleplay/$simulationId'
    | '/courses/'
    | '/courses/$courseId/'
    | '/courses/$courseId/lessons/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/achievements'
    | '/ai'
    | '/assessments'
    | '/certificates'
    | '/continue'
    | '/dashboard'
    | '/finance'
    | '/notifications'
    | '/profile'
    | '/ranking'
    | '/roleplay'
    | '/settings'
    | '/roleplay/$simulationId'
    | '/courses'
    | '/courses/$courseId'
    | '/courses/$courseId/lessons/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_app/achievements'
    | '/_app/ai'
    | '/_app/assessments'
    | '/_app/certificates'
    | '/_app/continue'
    | '/_app/courses'
    | '/_app/dashboard'
    | '/_app/finance'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/ranking'
    | '/_app/roleplay'
    | '/_app/settings'
    | '/_app/courses/$courseId'
    | '/_app/roleplay/$simulationId'
    | '/_app/courses/'
    | '/_app/courses/$courseId/'
    | '/_app/courses/$courseId/lessons/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/achievements': {
      id: '/_app/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assessments': {
      id: '/_app/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AppAssessmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/certificates': {
      id: '/_app/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AppCertificatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/continue': {
      id: '/_app/continue'
      path: '/continue'
      fullPath: '/continue'
      preLoaderRoute: typeof AppContinueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses': {
      id: '/_app/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AppCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ranking': {
      id: '/_app/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AppRankingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roleplay': {
      id: '/_app/roleplay'
      path: '/roleplay'
      fullPath: '/roleplay'
      preLoaderRoute: typeof AppRoleplayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses/': {
      id: '/_app/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof AppCoursesIndexRouteImport
      parentRoute: typeof AppCoursesRoute
    }
    '/_app/courses/$courseId': {
      id: '/_app/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof AppCoursesCourseIdRouteImport
      parentRoute: typeof AppCoursesRoute
    }
    '/_app/roleplay/$simulationId': {
      id: '/_app/roleplay/$simulationId'
      path: '/$simulationId'
      fullPath: '/roleplay/$simulationId'
      preLoaderRoute: typeof AppRoleplaySimulationIdRouteImport
      parentRoute: typeof AppRoleplayRoute
    }
    '/_app/courses/$courseId/': {
      id: '/_app/courses/$courseId/'
      path: '/'
      fullPath: '/courses/$courseId/'
      preLoaderRoute: typeof AppCoursesCourseIdIndexRouteImport
      parentRoute: typeof AppCoursesCourseIdRoute
    }
    '/_app/courses/$courseId/lessons/$lessonId': {
      id: '/_app/courses/$courseId/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/courses/$courseId/lessons/$lessonId'
      preLoaderRoute: typeof AppCoursesCourseIdLessonsLessonIdRouteImport
      parentRoute: typeof AppCoursesCourseIdRoute
    }
  }
}

interface AppCoursesCourseIdRouteChildren {
  AppCoursesCourseIdIndexRoute: typeof AppCoursesCourseIdIndexRoute
  AppCoursesCourseIdLessonsLessonIdRoute: typeof AppCoursesCourseIdLessonsLessonIdRoute
}

const AppCoursesCourseIdRouteChildren: AppCoursesCourseIdRouteChildren = {
  AppCoursesCourseIdIndexRoute: AppCoursesCourseIdIndexRoute,
  AppCoursesCourseIdLessonsLessonIdRoute:
    AppCoursesCourseIdLessonsLessonIdRoute,
}

const AppCoursesCourseIdRouteWithChildren =
  AppCoursesCourseIdRoute._addFileChildren(AppCoursesCourseIdRouteChildren)

interface AppCoursesRouteChildren {
  AppCoursesCourseIdRoute: typeof AppCoursesCourseIdRouteWithChildren
  AppCoursesIndexRoute: typeof AppCoursesIndexRoute
}

const AppCoursesRouteChildren: AppCoursesRouteChildren = {
  AppCoursesCourseIdRoute: AppCoursesCourseIdRouteWithChildren,
  AppCoursesIndexRoute: AppCoursesIndexRoute,
}

const AppCoursesRouteWithChildren = AppCoursesRoute._addFileChildren(
  AppCoursesRouteChildren,
)

interface AppRoleplayRouteChildren {
  AppRoleplaySimulationIdRoute: typeof AppRoleplaySimulationIdRoute
}

const AppRoleplayRouteChildren: AppRoleplayRouteChildren = {
  AppRoleplaySimulationIdRoute: AppRoleplaySimulationIdRoute,
}

const AppRoleplayRouteWithChildren = AppRoleplayRoute._addFileChildren(
  AppRoleplayRouteChildren,
)

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppAiRoute: typeof AppAiRoute
  AppAssessmentsRoute: typeof AppAssessmentsRoute
  AppCertificatesRoute: typeof AppCertificatesRoute
  AppContinueRoute: typeof AppContinueRoute
  AppCoursesRoute: typeof AppCoursesRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRankingRoute: typeof AppRankingRoute
  AppRoleplayRoute: typeof AppRoleplayRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppAiRoute: AppAiRoute,
  AppAssessmentsRoute: AppAssessmentsRoute,
  AppCertificatesRoute: AppCertificatesRoute,
  AppContinueRoute: AppContinueRoute,
  AppCoursesRoute: AppCoursesRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppRankingRoute: AppRankingRoute,
  AppRoleplayRoute: AppRoleplayRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
